name: Publish to conda

on:
  release:
    types: ['published', 'released', 'prereleased']

jobs:
  build-conda:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Install conda-build
      run: conda install -c conda-forge conda-build
    - name: Build the conda package
      run: conda-build .
    - name: upload the conda package
      run: anaconda upload --user miniufo --label main /home/runner/work/xgrads/xgrads*.tar.bz2
      env:
        ANACONDA_TOKEN: ${{ secrets.CONDA_API_TOKEN }} # Replace with the right name of your secret


