name: Publish to conda

on:
  release:
    types: ['released', 'prereleased']

jobs:
  build-conda:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: publish-to-conda
      uses: maxibor/conda-package-publish-action@v1.1
      with:
        subDir: './'
        AnacondaToken: ${{ secrets.CONDA_API_TOKEN }}


